version: '3'
services:
  app:
    build: app
    ports:
      - "8090:80"
    volumes:
      - "./app/:/home/app/"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      PYTHONPATH: /home/app

  front:
    build: front
    ports: 
      - "3000:3000"
    volumes:
      - "./front/:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - app
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password